### ISSUE TITLE
error in demo.py

### ISSUE THREAD

**Issue by amiltonwong** [paschalidoud/neural_parts#1]
Hi, @paschalidoud ,

When I run the demo.py using the following command, I got the following type error: 

```
# python demo.py ../config/dfaust_6.yaml --we ../demo/model_dfaust_6 --model_tag 50027_jumping_jacks:00135 --camera_target='-0.030173788,-0.10342446,-0.0021887198' --camera_position='0.076685235,-0.14528269,1.2060229' --up='0,1,0' --with_rotating_camera

Running code on cuda:0
Found 270 Dynamic Faust models
Keep 1/270 based on tags
Traceback (most recent call last):
  File "demo.py", line 210, in <module>
    main(sys.argv[1:])
  File "demo.py", line 172, in main
    for i in parts
  File "demo.py", line 172, in <listcomp>
    for i in parts
  File "/root2/anaconda3/envs/pytorch1.7/lib/python3.7/site-packages/simple_3dviz/renderables/mesh.py", line 317, in from_faces
    [vertices, faces, colors]
  File "/root2/anaconda3/envs/pytorch1.7/lib/python3.7/site-packages/numpy/core/_asarray.py", line 102, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/root2/anaconda3/envs/pytorch1.7/lib/python3.7/site-packages/torch/tensor.py", line 630, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

```
It seems some place should be converted to cpu type first.
Could you give some hints to solve this issue?

Thanks~

**Comment by paschalidoud** [comment]
Hi,

Adding `.cpu()` to lines 168 and 169 in the demo would fix it. If not the simplest quick fix until I do some testing is to run it with `CUDA_VISIBLE_DEVICES=''`.

I will do some more testing and push a fix. Thanks for letting me know.

Despoina

**Comment by amiltonwong** [comment]
Hi, @paschalidoud ,

Thanks for your reply.  I then add `.cpu()` as follows:
```
            vertices.cpu()[0, :, i],
            faces.cpu(),
```
The cpu type error is fixed. However, another error comes out as follows when executing demo.py:
```
Running code on cuda:0
Found 270 Dynamic Faust models
Keep 1/270 based on tags
Traceback (most recent call last):
  File "/root2/anaconda3/envs/pytorch1.7/lib/python3.7/site-packages/simple_3dviz/window/wx.py", line 76, in _on_paint
    self._mgl_context = moderngl.create_context()
  File "/root2/anaconda3/envs/pytorch1.7/lib/python3.7/site-packages/moderngl/context.py", line 1626, in create_context
    require, ctx.version_code))
ValueError: Requested OpenGL version 330, got version 300
Traceback (most recent call last):
  File "/root2/anaconda3/envs/pytorch1.7/lib/python3.7/site-packages/simple_3dviz/window/wx.py", line 76, in _on_paint
    self._mgl_context = moderngl.create_context()
  File "/root2/anaconda3/envs/pytorch1.7/lib/python3.7/site-packages/moderngl/context.py", line 1626, in create_context
    require, ctx.version_code))
ValueError: Requested OpenGL version 330, got version 300
Traceback (most recent call last):
  File "/root2/anaconda3/envs/pytorch1.7/lib/python3.7/site-packages/simple_3dviz/window/wx.py", line 76, in _on_paint
    self._mgl_context = moderngl.create_context()
  File "/root2/anaconda3/envs/pytorch1.7/lib/python3.7/site-packages/moderngl/context.py", line 1626, in create_context
    require, ctx.version_code))
ValueError: Requested OpenGL version 330, got version 300

```

It seems there's some error related to opengl version. I had installed `simple_3dviz==0.2.1`, `wxpython==4.0.4` in my environment.

Any hints to solve this issue?

Thanks~

**Comment by amiltonwong** [comment]
Supplement:
I then check OpenGL version by the following command:
`glxinfo | grep "OpenGL version"`
```
OpenGL version string: 4.6.0 NVIDIA 418.39
```
(My system is Ubuntu 16.04)

**Comment by paschalidoud** [comment]
Hi,

We have tested simple-3dviz with ``wxpython=4.0.7``. Do you want to try and see if upgrading the wxpython version solves this issue?

Please let me know if this doesn't work to look deeper into this :-)

Best,
Despoina

**Comment by paschalidoud** [comment]
I am closing the issue due to inactivity but feel free to reopen it if you are still experiencing problems.

Best,
Despoina
