### ISSUE TITLE
Error : RuntimeError: CUDA out of memory. Tried to allocate 30.00 MiB (GPU 0; 8.00 GiB total capacity; 5.97 GiB already allocated; 3.75 MiB free; 6.12 GiB reserved in total by PyTorch)

### ISSUE THREAD

**Issue by mahmoudEltaher** [paschalidoud/neural_parts#3]
Hi, @paschalidoud ,

When I run the demo.py using the following command, I got the following type error:
python scripts/train_network.py config/shapenet_5.yaml output/
Running code on cuda:0
experiment_directory output/AJEYHFV7Y
Save experiment statistics in AJEYHFV7Y
Found 10 MultiModelsShapeNetV1 models
Keep 10/10 based on train/test splits
Dataset has 10 elements
Found 10 MultiModelsShapeNetV1 models
Keep 0/10 based on train/test splits
Dataset has 0 elements
Traceback (most recent call last):
  File "scripts/train_network.py", line 288, in <module>
    main(sys.argv[1:])
  File "scripts/train_network.py", line 250, in main
    network, optimizer, loss_fn, metrics_fn, X, targets, config
  File "d:\cottbus\code\neural_parts-master\neural_parts\models\flexible_primitives.py", line 258, in train_on_batch
    F, network, targets, config
  File "d:\cottbus\code\neural_parts-master\neural_parts\models\flexible_primitives.py", line 214, in compute_predictions_from_features
    network.implicit_surface(F, targets[-1][:, :, :3])
  File "d:\cottbus\code\neural_parts-master\neural_parts\models\flexible_primitives.py", line 58, in implicit_surface
    y_latent, ldj = self.invertible_network.inverse(F, y)
  File "d:\cottbus\code\neural_parts-master\neural_parts\models\simple_nvp.py", line 166, in inverse
    x, ldji = self._call(l.inverse, F, x)
  File "d:\cottbus\code\neural_parts-master\neural_parts\models\simple_nvp.py", line 116, in _call
    return func(*args, **kwargs)
  File "d:\cottbus\code\neural_parts-master\neural_parts\models\simple_nvp.py", line 34, in inverse
    t = self.map_t(F_x1)
  File "C:\Users\Mahmoud Eltaher\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Mahmoud Eltaher\Anaconda3\lib\site-packages\torch\nn\modules\container.py", line 117, in forward
    input = module(input)
  File "C:\Users\Mahmoud Eltaher\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Mahmoud Eltaher\Anaconda3\lib\site-packages\torch\nn\modules\linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "C:\Users\Mahmoud Eltaher\Anaconda3\lib\site-packages\torch\nn\functional.py", line 1692, in linear
    output = input.matmul(weight.t())
RuntimeError: CUDA out of memory. Tried to allocate 30.00 MiB (GPU 0; 8.00 GiB total capacity; 5.97 GiB already allocated; 3.75 MiB free; 6.12 GiB reserved in total by PyTorch)

Could you give some hints to solve this issue?
Thanks,

**Comment by paschalidoud** [comment]
Hi,

This simply means that the model does not fit in your GPU. Standard operating procedure to fit it should be followed (e.g. reduce the batch size and/or reduce the size of the inputs and/or reduce the size of the model etc.).

I will close the issue as it is not specific to Neural Parts, feel free to reopen it if you think otherwise.

Best,
Despoina
